version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
sphinx:
  configuration: doc/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: doc/requirement.txt
formats:
   - pdf
   - epub
